# fly.toml app configuration file generated for happy-birthday-project on 2024-08-30T20:49:18+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'happy-birthday-project'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-2x'
